name: MyPy static code checking

on:
  push:
    branches:
      - master
      - github-actions
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    name: MyPy on
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing dependencies
        run: python -m pip install mypy pytest .

      # - name: Running MyPy static type checking on src and tests
      #   run: |
      #     mypy calculator
      #     mypy tests  

      - name: Running MyPy static type checking on src
        run: mypy calculator 

      - name: Running MyPy static type checking on tests
        run: mypy tests 